'use client';
import {useEffect,useState} from 'react';
import {Header,Footer} from '../marketplace';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {House,ArrowRight,ShieldCheck} from 'lucide-react';
import {safeReturnTo} from '../auth-policy';

export default function SignIn() {
 const [mode,setMode]=useState<'signin'|'signup'|'reset'>('signin'),[enabled,setEnabled]=useState<boolean|null>(null),[user,setUser]=useState<any>(null),[chatgpt,setChatgpt]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[returnTo,setReturnTo]=useState('/');
 useEffect(()=>{setReturnTo(safeReturnTo(new URLSearchParams(window.location.search).get('return_to')));fetch('/api/auth').then(r=>{if(!r.ok)throw Error();return r.json()}).then((d:any)=>{setEnabled(d.enabled);setChatgpt(d.chatgptAvailable);setUser(d.user)}).catch(()=>setError('Account services could not be reached. Please reload to try again.'))},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,email:form.get('email'),password:mode==='reset'?undefined:form.get('password')})});const d:any=await r.json();if(!r.ok)throw Error(d.error);if(mode==='reset')setMessage(d.message);else window.location.assign(returnTo);}catch(e:any){setError(e.message||'Please try again.')}finally{setBusy(false)}}
 async function signout(){setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'signout'})});if(!r.ok)throw Error();window.location.assign('/');}catch{setError('Unable to sign out. Please try again.');setBusy(false)}}
 return <><Header/><main className="signin-main"><section className="signin-story"><p className="eyebrow">YOUR PLACE STARTS HERE</p><h1>One account.<br/>Your next chapter.</h1><p>Keep the homes you love close. Share a property with its next owner. Find a place that feels like you.</p><div><ShieldCheck/><span>Your favorites and listings, together across devices.</span></div></section><section className="signin-card"><House size={30}/><h2>{user?'Welcome back.':mode==='signup'?'Make yourself at home.':mode==='reset'?'A fresh start.':'Welcome home.'}</h2><p>{user?user.email:mode==='reset'?'We’ll email you a link to reset your password.':'Sign in to save your favorites and list your property.'}</p>{error&&<p className="notice" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}{user?<><a className="primary" href={returnTo}>Continue to Haven <ArrowRight size={17}/></a>{enabled?<Button variant="outline" onClick={signout} disabled={busy}>Sign out</Button>:<a className="outline" href="/signout-with-chatgpt?return_to=%2Fsignin" target="_top">Sign out</a>}</>:enabled===null?<p role="status">{error?'Please refresh this page to reconnect.':'Loading sign-in…'}</p>:!enabled?<><p className="sample-note">{chatgpt?"Email sign-in is being set up. You can continue with ChatGPT today.":"Email sign-in is being configured. Please check back soon."}</p>{chatgpt&&<a className="primary" target="_top" href={'/signin-with-chatgpt?return_to='+encodeURIComponent(returnTo)}>Continue with ChatGPT <ArrowRight size={17}/></a>}</>:<><form onSubmit={submit}><label htmlFor="email">Email address</label><Input id="email" name="email" type="email" autoComplete="email" placeholder="you@example.com" required maxLength={254}/>{mode!=='reset'&&<><label htmlFor="password">Password</label><Input id="password" name="password" type="password" autoComplete={mode==='signup'?'new-password':'current-password'} required minLength={mode==='signup'?8:1} maxLength={128}/>{mode==='signup'&&<small>Use at least 8 characters.</small>}</>}<Button className="primary" disabled={busy} type="submit">{busy?'Please wait…':mode==='signup'?'Create account':mode==='reset'?'Send reset link':'Sign in'}<ArrowRight size={17}/></Button></form><div className="signin-links">{mode==='signin'?<><button onClick={()=>{setMode('reset');setError('');setMessage('')}}>Forgot password?</button><button onClick={()=>{setMode('signup');setError('');setMessage('')}}>New to Haven? Create an account</button></>:<button onClick={()=>{setMode('signin');setError('');setMessage('')}}>Back to sign in</button>}</div><p className="small muted">For your privacy, sessions last up to one hour.</p></>}</section></main><Footer/></>;
}
