'use client';
import {useState} from 'react';
import {Header,Footer} from './marketplace';
import {ArrowLeft,ArrowRight,Upload,Check,X,House} from 'lucide-react';
const steps=['The basics','Photos & details','Location & contact','Review'];
export default function ListingForm(){const[step,setStep]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[success,setSuccess]=useState('');const[data,setData]=useState<any>({title:'',mode:'Buy',type:'House',price:'',beds:3,baths:2,area:'',description:'',photos:[],amenities:[],address:'',city:'',state:'',zip:'',contact:'',email:'',phone:'',role:'Owner'});const[id]=useState(()=>crypto.randomUUID());
 function change(key:string,value:any){setData((d:any)=>({...d,[key]:value}))}
 async function upload(files:FileList|null){if(!files)return;if(data.photos.length+files.length>8){setError('You can add up to 8 photos.');return}setUploading(true);setError('');try{for(const file of Array.from(files)){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('Use JPG, PNG, or WebP photos up to 5 MB each.');const body=new FormData();body.append('photo',file);const r=await fetch('/api/photos',{method:'POST',body});const d:any=await r.json();if(!r.ok)throw Error(d.error);setData((p:any)=>({...p,photos:[...p.photos,d.url]}));}}catch(e:any){setError(e.message)}finally{setUploading(false)}}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(step===1&&data.photos.length===0){setError('Add at least one photo to help people discover your property.');return}if(step<3){setStep(step+1);window.scrollTo({top:0,behavior:'smooth'});return}setBusy(true);try{const r=await fetch('/api/properties',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,id,price:Number(data.price),beds:Number(data.beds),baths:Number(data.baths),area:Number(data.area)})});const result:any=await r.json();if(!r.ok)throw Error(result.error);setSuccess(result.id);window.scrollTo({top:0,behavior:'smooth'});}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const field=(key:string,label:string,props:any={})=><label className={props.wide?'wide':''}>{label}<input {...Object.fromEntries(Object.entries(props).filter(([k])=>k!=='wide'))} value={data[key]} onChange={e=>change(key,e.target.value)} required/></label>;
 return <><Header/><main className="listing-main"><a className="back" href="/"><ArrowLeft size={17}/>Back to homes</a>{success?<section className="success"><div className="success-icon"><Check size={32}/></div><p className="eyebrow">WELCOME TO THE NEIGHBORHOOD</p><h1>Your property is listed.</h1><p>{data.title} is now available to browse on Haven.</p><a className="primary" href={'/property/'+success}>View your property <ArrowRight size={18}/></a><a className="back" href="/">Return to all homes</a></section>:<><section className="listing-heading"><p className="eyebrow">MAKE ROOM FOR THE NEXT CHAPTER</p><h1>A great home deserves to be found.</h1><p>Add your property in a few simple steps.</p></section><ol className="steps">{steps.map((s,i)=><li className={step===i?'current':step>i?'done':''} key={s}><span>{step>i?<Check size={16}/>:i+1}</span>{s}</li>)}</ol><form className="listing-form" onSubmit={submit}><h2>{steps[step]}</h2><p className="muted">{['Start with the essentials buyers and renters want to know.','Bring your home to life. Your first photo is the cover image.','Help people find the property and reach the right person.','Take one last look. These details will appear on your listing.'][step]}</p>{error&&<div className="notice" role="alert">{error}</div>}
 {step===0&&<div className="fields"><fieldset className="wide"><legend>I want to</legend><div className="choice-row">{['Buy','Rent'].map(m=><button type="button" aria-pressed={data.mode===m} className={data.mode===m?'choice chosen':'choice'} key={m} onClick={()=>change('mode',m)}><House size={20}/>{m==='Buy'?'Sell my property':'Rent out my property'}</button>)}</div></fieldset>{field('title','Listing title',{placeholder:'e.g. Sunlit home with a private garden',minLength:5,maxLength:100,wide:true})}<label>Property type<select value={data.type} onChange={e=>change('type',e.target.value)}>{['House','Apartment','Townhouse','Villa'].map(t=><option key={t}>{t}</option>)}</select></label>{field('price',data.mode==='Buy'?'Asking price (USD)':'Monthly rent (USD)',{type:'number',min:1,max:1000000000,placeholder:data.mode==='Buy'?'685000':'2500'})}{field('beds','Bedrooms',{type:'number',min:0,max:50})}{field('baths','Bathrooms',{type:'number',min:1,max:50,step:.5})}{field('area','Interior area (sq ft)',{type:'number',min:1,max:1000000,placeholder:'1850'})}</div>}
 {step===1&&<><label className="upload-zone"><Upload size={30}/><strong>{uploading?'Uploading your photos…':'Choose property photos'}</strong><span>JPG, PNG, or WebP · Up to 8 photos · 5 MB each</span><input type="file" aria-label="Property photos" accept="image/jpeg,image/png,image/webp" multiple disabled={uploading} onChange={e=>{upload(e.target.files);e.target.value=''}}/></label><div className="upload-previews">{data.photos.map((src:string,i:number)=><div key={src}><img src={src} alt={'Uploaded property photo '+(i+1)}/>{i===0&&<span>Cover</span>}<button type="button" aria-label={'Remove photo '+(i+1)} onClick={()=>change('photos',data.photos.filter((_:string,j:number)=>i!==j))}><X size={16}/></button></div>)}</div><div className="fields"><label className="wide">About the property<textarea required minLength={30} maxLength={5000} rows={6} placeholder="What makes this home special? Describe the layout, features, and neighborhood." value={data.description} onChange={e=>change('description',e.target.value)}/></label><fieldset className="wide"><legend>Amenities</legend><div className="amenity-options">{['Parking','Private garden','Balcony','Swimming pool','Air conditioning','Laundry','Elevator','Storage'].map(a=><label key={a}><input type="checkbox" checked={data.amenities.includes(a)} onChange={e=>change('amenities',e.target.checked?[...data.amenities,a]:data.amenities.filter((x:string)=>x!==a))}/>{a}</label>)}</div></fieldset></div></>}
 {step===2&&<div className="fields">{field('address','Street address',{minLength:5,maxLength:200,wide:true,placeholder:'1428 Willow Creek Lane'})}{field('city','City',{minLength:2,maxLength:80,placeholder:'Austin'})}{field('state','State / region',{minLength:2,maxLength:80,placeholder:'Texas'})}{field('zip','ZIP / postal code',{minLength:3,maxLength:15,placeholder:'78704'})}<label>I am the<select value={data.role} onChange={e=>change('role',e.target.value)}><option>Owner</option><option>Agent</option></select></label>{field('contact','Contact name',{minLength:2,maxLength:100})}{field('email','Email address',{type:'email',maxLength:150})}{field('phone','Phone number',{type:'tel',minLength:7,maxLength:25,placeholder:'+1 512 555 0123'})}<p className="wide small muted">Your address and contact details will be visible on the property listing.</p></div>}
 {step===3&&<div className="review"><img src={data.photos[0]} alt="Property cover"/><div><p className="eyebrow">FOR {data.mode==='Buy'?'SALE':'RENT'} · {data.type}</p><h2>{data.title}</h2><strong className="big-price">${Number(data.price).toLocaleString()}{data.mode==='Rent'?' / month':''}</strong><p>{data.beds} beds · {data.baths} baths · {Number(data.area).toLocaleString()} sq ft</p><p>{data.address}, {data.city}, {data.state} {data.zip}</p></div><p className="wide description">{data.description}</p><p className="wide">{data.amenities.join(' · ')||'No amenities selected'}</p><div className="wide review-contact"><strong>{data.contact} · {data.role}</strong><p>{data.email} · {data.phone}</p><p>{data.photos.length} photo{data.photos.length!==1?'s':''}</p></div><label className="wide consent"><input type="checkbox" required/> I confirm these details are accurate and I am authorized to list this property.</label></div>}
 <div className="form-actions"><button className="outline" type="button" onClick={()=>{setStep(Math.max(0,step-1));setError('')}} disabled={step===0||busy}>Back</button><span>Step {step+1} of 4</span><button className="primary" disabled={uploading||busy}>{busy?'Publishing…':step===3?'Publish property':'Continue'}<ArrowRight size={17}/></button></div></form></>}</main><Footer/></>
}
